/*
 * DMA_Map.c
 *
 *  Created on: Aug 31, 2025
 *      Author: adool
 */
#include "dma_map.h"

// Global buffers
uint8_t uart_rx_buf[1024];
uint8_t uart_tx_buf[1024];

// External handles (generated by CubeMX)
extern UART_HandleTypeDef huart1;
extern UART_HandleTypeDef huart2;
extern UART_HandleTypeDef huart3;
extern UART_HandleTypeDef huart4;
extern UART_HandleTypeDef huart5;
extern UART_HandleTypeDef huart6;
// -----------------------------------------
// Generic DMA setup
// -----------------------------------------
void SetupDMA(dma_src_t srcType, void *src, dma_dst_t dstType, void *dst, size_t size) {

	if (srcType == SRC_MEMORY && dstType == DST_PERIPHERAL) {
		// Memory -> UART TX
		HAL_UART_Transmit_DMA((UART_HandleTypeDef*) dst, (uint8_t*) src, size);
	} else if (srcType == SRC_PERIPHERAL && dstType == DST_MEMORY) {
		// UART RX -> Memory
		HAL_UARTEx_ReceiveToIdle_DMA((UART_HandleTypeDef*) src, (uint8_t*) dst,
				size);
		__HAL_DMA_DISABLE_IT(((UART_HandleTypeDef* )src)->hdmarx, DMA_IT_HT);
		// disable half-transfer interrupts
	} else if (srcType == SRC_PERIPHERAL && dstType == DST_PERIPHERAL) {
		// Two-stage: UART RX -> staging buffer -> UART TX
		HAL_UARTEx_ReceiveToIdle_DMA((UART_HandleTypeDef*) src, uart_rx_buf,
				size);
		__HAL_DMA_DISABLE_IT(((UART_HandleTypeDef* )src)->hdmarx, DMA_IT_HT);

		// When Idle occurs, we’ll forward from uart_rx_buf → dst UART in callback
	}
}
